import test from 'node:test';
import assert from 'node:assert/strict';
import { plotAt, sortedProjects, visualStage, movePlayer } from '../src/exploration.mjs';
import { PLACES, matchLocation, residentGroups } from '../src/locations.mjs';
import { configuration, publicBundle } from '../src/bundle.mjs';
import { sampleTown } from '../src/sample.mjs';
import { capture } from '../server/github.mjs';

test('200 plots are unique, compact, and stable when the collection grows',()=>{const first=Array.from({length:20},(_,i)=>plotAt(i)),full=Array.from({length:200},(_,i)=>plotAt(i));assert.deepEqual(first,full.slice(0,20));assert.equal(new Set(full.map(p=>`${p.x},${p.z}`)).size,200);assert.ok(full.every(p=>Math.abs(p.x)<=8&&Math.abs(p.z)<=8));});
test('sorting is independent of plot identity and puts unknown metrics last',()=>{const b=sampleTown(),original=JSON.stringify(b);const snap=b.history.snapshots.at(-1);const sorted=sortedProjects(b.event.projects,snap,'commits');const record=p=>snap.projects.find(r=>r.projectId===p.id);assert.ok(record(sorted[0]).metrics.commits>=record(sorted.at(-1)).metrics.commits);assert.equal(JSON.stringify(b),original);assert.equal(visualStage('townhouse'),'complete');assert.equal(visualStage('decorated'),'complete');});
test('walking cannot cross walls or bounds but the front door triggers entry',()=>{const p={id:'one',plot:{x:0,z:0}},r={projectId:'one',stage:'cottage'},bounds={minX:-5,maxX:5,minZ:-5,maxZ:5};assert.equal(movePlayer({x:2,z:0},{x:-.3,z:0},[p],[r],bounds).position.x,2);assert.equal(movePlayer({x:-.45,z:1.9},{x:0,z:-.2},[p],[r],bounds).enter,'one');assert.equal(movePlayer({x:4.9,z:3},{x:1,z:0},[p],[r],bounds).position.x,5);assert.equal(movePlayer({x:-.45,z:1.9},{x:0,z:-.2},[p],[{...r,stage:'foundation'}],bounds).enter,null);});
test('ambiguous places are not guessed and resident counts deduplicate a builder',()=>{assert.equal(matchLocation('Paris / Berlin'),null);assert.equal(matchLocation('Earth'),null);assert.equal(matchLocation('San Francisco, CA').label,'San Francisco');const b=sampleTown();b.event.residentMap={enabled:true,fetchProfiles:false};b.event.projects.slice(0,2).forEach(p=>{p.builder={name:'Same person',url:'https://github.com/same',location:{label:'Paris',lat:48.86,lon:2.35,source:'manual'}};});const groups=residentGroups(b.event);assert.equal(groups.length,1);assert.equal(groups[0].residents,1);assert.equal(groups[0].projects.length,2);b.event.collectionType='personal';assert.deepEqual(residentGroups(b.event),[]);});
test('disabled map removes location from exported public data',()=>{const b=sampleTown();b.event.residentMap={enabled:false,fetchProfiles:false};b.event.projects[0].builder.locationText='Do not export';b.event.projects[0].builder.location={label:'Paris',lat:48.86,lon:2.35,source:'manual'};assert.equal(JSON.stringify(publicBundle(b)).includes('Do not export'),false);assert.equal(publicBundle(b).event.projects[0].builder.location,undefined);b.event.collectionType='personal';b.event.residentMap.enabled=true;assert.throws(()=>publicBundle(b),/multi-builder/);});
test('public profile requests occur only when the map is explicitly enabled',async()=>{let profiles=0;const fetcher=async url=>{if(url.includes('/users/')){profiles++;return Response.json({type:'User',location:'Berlin, Germany'});}if(url.includes('/commits?'))return Response.json([{sha:'a'}]);return Response.json({name:'test',private:false,size:1,default_branch:'main',stargazers_count:0,forks_count:0,owner:{type:'User',login:'alice',avatar_url:'https://avatars.githubusercontent.com/u/1'}});};const event=configuration({name:'Map',repositories:['https://github.com/alice/one','https://github.com/alice/two']});await capture(event,null,null,fetcher);assert.equal(profiles,0);event.residentMap={enabled:true,fetchProfiles:true};const result=await capture(event,null,null,fetcher);assert.equal(profiles,1);assert.equal(result.bundle.event.projects[0].builder.location.label,'Berlin');});
