import type {Bundle,Project} from './types';
import {icon} from './ui/icons';

export const html=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
type Translate=(en:string,zh:string)=>string;

/** One shared entrance, planning and town header. 入口、规划与小镇共用。 */
export function gameHeader(t:Translate,session:{login:string|null;avatar?:string|null;authenticated:boolean},language:string,compactProfile=false) {
  const profileLabel=session.authenticated?t(`Sync exploration for ${session.login}`,`同步 ${session.login} 的探索进度`):t('Sign in with GitHub','通过 GitHub 登录');
  return `<header class="map-header"><button id="home" class="wood-logo" aria-label="buildergame">${icon('house')}<strong>buildergame</strong><small>BUILD · SHIP · GROW</small></button><div class="player-actions"><button id="language" class="hud-button" aria-label="${t('Switch to Chinese','切换到英文')}">${language==='en'?'中文':'EN'}</button><button id="player-login" class="profile-chip hud-button ${compactProfile?'profile-icon hinted-control':''}" aria-label="${html(profileLabel)}" ${compactProfile?'aria-describedby="player-hint"':''}>${session.avatar?`<img src="${html(session.avatar)}" alt="" referrerpolicy="no-referrer">`:`<span class="guest-face" aria-hidden="true">${icon('user-round')}</span>`}<span class="${compactProfile?'control-hint':'profile-copy'}" ${compactProfile?'id="player-hint" role="tooltip"':''}><strong>${html(session.login||t('Guest explorer','访客探索者'))}</strong><small>${session.authenticated?t('GitHub connected','已连接 GitHub'):t('Sign in with GitHub','通过 GitHub 登录')}</small></span></button>${session.authenticated?`<button id="logout" class="hud-button" aria-label="${t('Sign out','退出')}">${icon('arrow-right')}<span>${t('Sign out','退出')}</span></button>`:''}</div></header>`;
}

export function gameLayout(bundle:Bundle,index:number,filter:string,t:Translate) {
  const landscape=bundle.event.landscape||'flat',total=bundle.event.projects.length;
  const townSettings=bundle.event.sampleData
    ? `<details class="sample-tour-picker"><summary class="hud-button" aria-label="${t('Tour landscapes','游览地形')}">${icon('map')}<span>${t('Tour landscapes','游览地形')}</span></summary><div class="sample-tour-options paper-panel" role="group" aria-label="${t('Sample landscapes','示例地形')}">${(['flat','valley','clouds'] as const).map((mode,i)=>`<button type="button" class="hud-button sample-tour-choice" data-tour-landscape="${mode}" aria-pressed="${mode===landscape}"><img src="${import.meta.env.BASE_URL}ui/landscapes/${mode}.png" alt="" width="80" height="45"><span>${[t('Flat town','平地城镇'),t('Valley','山谷'),t('Cloud town','云端城镇')][i]}</span></button>`).join('')}</div></details>`
    : `<button id="manage" class="hud-button">${icon('settings')}<span>${t('Town settings','城镇设置')}</span></button>`;
  return `<main class="game map-game"><div id="scene" class="scene"></div>
  <nav class="map-nav" aria-label="${t('Town navigation','小镇导航')}"><button id="map-home" class="hud-button active">${icon('map')}<span>${t('Town map','小镇地图')}</span></button><button id="show-projects" class="hud-button">${icon('projects')}<span>${t('Projects','项目')}</span></button><button id="show-exploration" class="hud-button">${icon('compass')}<span>${t('Exploration','探索进度')}</span></button>${townSettings}<button data-export class="hud-button">${icon('download')}<span>${t('Save town','保存小镇')}</span></button></nav>
  <div class="town-stats" id="town-stats" aria-label="${t('Town totals','小镇统计')}"></div>
  <aside class="quest-stack"><section class="hud-glass exploration-panel"><h2>${t('Your exploration','你的探索')}</h2><div class="quest-line"><span>${t('Meet the builders','认识开发者')}</span><b id="visited-count">0 / ${total}</b></div><progress id="visited-bar" value="0" max="${total}" aria-label="${t('Projects discovered','已探索项目')}"></progress><p id="progress-status">${t('Saved on this device','保存在当前设备')}</p><button id="next-project" class="hud-button">${t('Discover a project','发现一个项目')}</button></section><section class="hud-glass town-info"><h2>${t('About this town','关于小镇')}</h2><strong>${html(bundle.event.name)}</strong><p>${t(`${total} projects`,`${total} 个项目`)} · ${t({flat:'Flat town',valley:'Valley',clouds:'Cloud districts'}[landscape],{flat:'平地城镇',valley:'山谷',clouds:'云端片区'}[landscape])}</p>${bundle.event.sampleData?`<small>${t('Fictional sample data','虚构示例数据')}</small>`:''}</section></aside>
  <aside class="project-panel hud-glass" id="project-panel" hidden><div class="panel-title"><h2>${t('Meet the neighbors','认识邻居')}</h2><button id="close-projects" class="hud-button icon-button" aria-label="${t('Close projects','关闭项目列表')}">${icon('x')}</button></div><label class="sr-only" for="search">${t('Search projects','搜索项目')}</label><input type="search" id="search" placeholder="${t('Find a project or builder…','查找项目或开发者…')}" value="${html(filter)}"><div class="project-list" id="project-list"></div></aside>
  <section class="explorer-badge hud-glass"><span class="explorer-avatar" id="explorer-avatar" aria-hidden="true">${icon('user-round')}</span><div><strong>${t('Explorer','探索者')}</strong><p id="explorer-count"></p><progress id="explorer-bar" max="${total}" value="0" aria-label="${t('Projects discovered','已探索项目')}"></progress></div></section>
  <div class="camera-controls" aria-label="${t('Camera controls','视角控制')}"><button id="zoom-in" class="hud-button icon-button" aria-label="${t('Zoom in','放大')}">${icon('plus')}</button><button id="zoom-out" class="hud-button icon-button" aria-label="${t('Zoom out','缩小')}">${icon('minus')}</button><button id="reset" class="hud-button icon-button" aria-label="${t('Reset camera','重置视角')}">${icon('reset')}</button></div>
  <section class="map-minimap"><span class="north" aria-hidden="true">N</span><canvas id="minimap" width="240" height="240" aria-label="${t('Town minimap. Use the project list for keyboard navigation.','小镇缩略地图，可通过项目列表使用键盘导航。')}"></canvas><small>${t('Pick a plot to explore','选择地块开始探索')}</small></section>
  <div class="timeline hud-glass"><div class="timeline-heading"><span>${t('Town time machine','小镇时光机')}</span><span id="snapshot-date"></span></div><div class="timeline-controls"><button id="play" class="hud-button icon-button" aria-label="${t('Play history','播放历史')}">${icon('play')}</button><input id="timeline" type="range" min="0" max="${bundle.history.snapshots.length-1}" value="${index}" aria-label="${t('Snapshot timeline','快照时间线')}"><span id="snapshot-count"></span></div><p id="snapshot-label" role="status" aria-live="polite"></p></div>
  <p class="scene-tip">${t('Select a sign to meet its builder · Drag to explore','点击木牌认识开发者 · 拖动游览小镇')}</p></main>`;
}

/** A visitor card keeps the project introduction and its destination in view. */
export function projectCard(p:Project,body:string,links:string,_stats:string,t:Translate) {
  return `<h2 id="detail-title">${html(p.name)}</h2><div class="builder-line">${p.builder.avatar?`<img src="${html(p.builder.avatar)}" alt="" referrerpolicy="no-referrer">`:`<span aria-hidden="true">${html(p.builder.name.slice(0,1))}</span>`}<span class="builder-name">${html(p.builder.name)}</span></div><p class="project-description">${html(p.description||t('This builder has not added a project description yet.','开发者还没有添加项目简介。'))}</p>${body?`<div class="project-data-note">${body}</div>`:''}<div class="detail-links">${links}</div>`;
}
