import type {Bundle,Project} from './types';
export const html=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
type Translate=(en:string,zh:string)=>string;
export function gameHeader(t:Translate,session:{login:string|null;avatar?:string|null;authenticated:boolean},language:string) {
  return `<header class="map-header"><button id="home" class="wood-logo"><span>⌂</span><strong>buildergame</strong><small>BUILD · SHIP · GROW</small></button><div class="player-actions"><button id="language" class="hud-button">${language==='en'?'中文':'EN'}</button><button id="player-login" class="profile-chip hud-glass">${session.avatar?`<img src="${html(session.avatar)}" alt="" referrerpolicy="no-referrer">`:'<span class="guest-face">⌖</span>'}<span><strong>${html(session.login||t('Guest explorer','访客探索者'))}</strong><small>${session.authenticated?t('GitHub connected','已连接 GitHub'):t('Sign in with GitHub','通过 GitHub 登录')}</small></span></button>${session.authenticated?`<button id="logout" class="hud-button">${t('Sign out','退出')}</button>`:''}</div></header>`;
}
export function gameLayout(bundle:Bundle,index:number,filter:string,t:Translate) {
  const landscape=bundle.event.landscape||'flat';
  return `<main class="game map-game"><div id="scene" class="scene"></div>
  <nav class="map-nav" aria-label="${t('Town navigation','小镇导航')}"><button id="map-home" class="hud-button active">⌂ <span>${t('Town map','小镇地图')}</span></button><button id="show-projects" class="hud-button">▦ <span>${t('Projects','项目')}</span></button><button id="show-exploration" class="hud-button">⌖ <span>${t('Exploration','探索进度')}</span></button><button id="manage" class="hud-button">⚙ <span>${t('Town settings','城镇设置')}</span></button><button data-export class="hud-button">↓ <span>${t('Save town','保存小镇')}</span></button></nav>
  <div class="town-stats" id="town-stats"></div>
  <aside class="quest-stack"><section class="hud-glass exploration-panel"><h2>✦ ${t('Your exploration','你的探索')}</h2><div class="quest-line"><span>${t('Meet the builders','认识开发者')}</span><b id="visited-count">0 / ${bundle.event.projects.length}</b></div><progress id="visited-bar" value="0" max="${bundle.event.projects.length}"></progress><p id="progress-status">${t('Saved on this device','保存在当前设备')}</p><button id="next-project" class="hud-button small">${t('Discover a project','发现一个项目')} →</button></section><section class="hud-glass town-info"><h2>⚑ ${t('About this town','关于小镇')}</h2><strong>${html(bundle.event.name)}</strong><p>${t(`${bundle.event.projects.length} projects`,`${bundle.event.projects.length} 个项目`)} · ${t({flat:'Flat town',valley:'Valley',clouds:'Cloud districts'}[landscape],{flat:'平地城镇',valley:'山谷',clouds:'云端片区'}[landscape])}</p>${bundle.event.sampleData?`<small>${t('FICTIONAL SAMPLE DATA','虚构示例数据')}</small>`:''}</section></aside>
  <aside class="project-panel hud-glass" id="project-panel" hidden><div class="panel-title"><h2>${t('Meet the neighbors','认识邻居')}</h2><button id="close-projects" class="hud-button small" aria-label="${t('Close projects','关闭项目列表')}">×</button></div><label class="sr-only" for="search">${t('Search projects','搜索项目')}</label><input type="search" id="search" placeholder="${t('Find a project or builder…','查找项目或开发者…')}" value="${html(filter)}"><div class="project-list" id="project-list"></div></aside>
  <section class="explorer-badge hud-glass"><span class="explorer-avatar" id="explorer-avatar">⌖</span><div><strong>${t('Explorer','探索者')}</strong><p id="explorer-count"></p><progress id="explorer-bar" max="${bundle.event.projects.length}" value="0"></progress></div></section>
  <div class="camera-controls"><button id="zoom-in" aria-label="${t('Zoom in','放大')}">+</button><button id="zoom-out" aria-label="${t('Zoom out','缩小')}">−</button><button id="reset" aria-label="${t('Reset camera','重置视角')}">↺</button></div>
  <section class="map-minimap"><span class="north">N</span><canvas id="minimap" width="240" height="240" aria-label="${t('Town minimap. Use the project list for keyboard navigation.','小镇缩略地图，可通过项目列表使用键盘导航。')}"></canvas><small>${t('Click a plot to explore','点击地块探索')}</small></section>
  <div class="timeline hud-glass"><div class="timeline-heading"><span>◷ ${t('TOWN TIME MACHINE','小镇时光机')}</span><span id="snapshot-date"></span></div><div class="timeline-controls"><button id="play" aria-label="${t('Play history','播放历史')}">▶</button><input id="timeline" type="range" min="0" max="${bundle.history.snapshots.length-1}" value="${index}" aria-label="${t('Snapshot timeline','快照时间线')}"><span id="snapshot-count"></span></div><p id="snapshot-label" role="status" aria-live="polite"></p></div>
  <p class="scene-tip">${t('Explore the town · Select a sign to meet its builder · Drag to orbit','探索小镇 · 点击木牌认识开发者 · 拖动旋转')}</p></main>`;
}
export function projectCard(p:Project,body:string,links:string,stats:string,t:Translate) {
  return `<div class="project-intro"><div class="project-preview"><img id="project-preview-image" hidden alt="${t('Building view','建筑视图')}"><span id="project-preview-placeholder">⌂</span></div><div><h2 id="detail-title">${html(p.name)}</h2><small>${t('A project in this neighborhood','这个街区里的项目')}</small><div class="builder-line">${p.builder.avatar?`<img src="${html(p.builder.avatar)}" alt="" referrerpolicy="no-referrer">`:`<span>${html(p.builder.name.slice(0,1))}</span>`}<strong>${html(p.builder.name)}</strong></div></div></div><p class="builder-bio">${html(p.builder.bio||'')}</p><div class="project-tags"><span>GitHub</span><span>${t('Public repository','公开仓库')}</span></div><h3>${t('About the project','项目简介')}</h3><p>${html(p.description)}</p>${body}<div class="card-metrics">${stats}</div><div class="detail-links">${links}</div>`;
}
